spring:
  application:
    name: CRYPTO-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/cryto
    ### i typed wrong here so i got a db named cryto
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost